#!/bin/bash
# Usage 
# ./collagerecipe RECIPE_FILE OUTPUT_NAME
# Try it like this
# ./collagerecipe example.recipe `whoami`

python generate_json.py $1
webkit2png -F -z 2.8 --delay=2 -o $2 http://localhost:8000
open $2-full.png